export type RootStackParamList = {
  Splash: undefined;
  Landing: undefined;
  Login: undefined;
  ForgotPassword: undefined;
  Register_Step1: undefined;
  Register_EmailVerify: { email: string; userId: string };
  Register_Step2: { phone: string; userId: string };
  Register_Step3: undefined;
  Register_Step4: undefined;
  Register_Step5: undefined;
  Register_Step6: undefined;
  Register_Step7: undefined;
  Verification: undefined;
  Onboarding: undefined;
  Auth: undefined;
  MainTabs: { screen?: string; params?: any } | undefined;
  Chat: { type: 'individual' | 'group'; chatId: string; userName: string; userPhoto?: string; userId?: string };
  GroupDetails: { tripId: string };
  UserDetail: { userId: string };
  EditProfile: undefined;
  Settings: undefined;
  WhoLikedMe: undefined;
  CreateTrip: undefined;
  TripDetail: { tripId: string };
  Notifications: undefined;
  PostDetail: { postId: string };
  MyMatches: undefined;
  AIItinerary: { trip: any };
  PlaceDetails: { place: any };
  AllDestinations: undefined;
  SavedDestinations: undefined;
  TermsScreen: undefined;
  PrivacyScreen: undefined;
  PrivacySafety: undefined;
  HelpSupport: undefined;
  About: undefined;
  PlaceDiscovery: undefined;
  DayPlanner: { query: string; moods?: string[] };
  CategoryDetails: { title: string, places: any[], excludeIds?: string[] };
  LocationPicker: { onSelect: (location: { name: string; lat: number; lng: number }) => void, initialLocation?: { lat: number, lng: number } };
  LyraItinerary: { caption?: string; location?: string; postId?: string; itinerary?: any; id?: string };
  PostDetailRedirect: { initialTab?: string } | undefined;
  LyraRedirect: undefined;
  TripHistory: undefined;
  DeleteAccount: undefined;
  ProfileViews: undefined;
  AdminPanel: undefined;
  Checklist: undefined;
  ChecklistDetail: { checklistId: string };
};
